name: Production Approval Lab

on:
  workflow_dispatch:

jobs:

  deploy-prod:

    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:

      - name: Production Deploy
        run: echo "Deploying to Production"
