name: Docker Build Lab

on:
  workflow_dispatch:

jobs:

  docker-build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t myapp:v1 .

      - name: List Images
        run: |
          docker images
