name: ECR Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  docker-ecr:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      - name: Debug Context
        run: |
          echo "Repository=${{ github.repository }}"
          echo "Ref=${{ github.ref }}"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::450690783347:role/GitHubActionsECRRole
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t github-actions-demo .

      - name: Tag Docker Image
        run: |
          docker tag github-actions-demo:latest \
          450690783347.dkr.ecr.us-east-1.amazonaws.com/github-actions-demo:latest

      - name: Push Docker Image
        run: |
          docker push \
          450690783347.dkr.ecr.us-east-1.amazonaws.com/github-actions-demo:latest
