name: Security Lab1

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  security-demo:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Security Check
        run: |
          echo "Least privilege permissions enabled"
