name: Trigger Lab

on:
  push:
    branches:
      - main

jobs:
  trigger-test:

    runs-on: ubuntu-latest

    steps:
      - name: Display Trigger Information
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Event: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
